source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/titer18/MebSpecs'
platform:ios, '10.0'

target 'Example' do
    inhibit_all_warnings!
    pod 'SelectProject', :path => '../'
end
